(()=>{
 const token=sessionStorage.getItem('htd_token'); const headers={Authorization:'Bearer '+token,'Content-Type':'application/json'};
 const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const toast=m=>{const t=document.getElementById('toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),3000)};
 async function api(url,opt={}){const r=await fetch(url,{...opt,headers:{...headers,...(opt.headers||{})}});const d=await r.json();if(!r.ok)throw new Error(d.message||'Request failed');return d}
 function predictionPage(){
  const p=document.getElementById('page-predictions'); if(!p)return;
  p.innerHTML=`<div class="intro-row"><div><h2>Isolation Forest AI Engine</h2><p>Train on doctor-specific historical behavior and score live activity without mobile self-approval.</p></div><div class="actions"><button class="button secondary" id="generateMl">Generate 1,200 Reports + History</button><button class="button" id="trainMl">Train Isolation Forest</button></div></div>
  <div class="notice"><strong>Insider policy:</strong> a doctor cannot clear a Critical prediction. Export All is blocked, the session is terminated, and evidence is retained for administrator investigation.</div>
  <div class="metric-grid four"><article class="metric-card"><div class="metric-label">Model status</div><div class="metric-value" id="mlStatus">Loading</div></article><article class="metric-card"><div class="metric-label">Training samples</div><div class="metric-value" id="mlSamples">0</div></article><article class="metric-card"><div class="metric-label">Doctors modeled</div><div class="metric-value" id="mlDoctors">0</div></article><article class="metric-card"><div class="metric-label">Reports dataset</div><div class="metric-value" id="mlReports">1,200</div></article></div>
  <div class="dashboard-grid"><article class="panel"><h3>Live behavior test</h3><div class="settings-form"><div class="field"><label>Doctor</label><select id="mlDoctor"><option value="DOC001">DOC001 — Dr. Arjuna</option><option value="DOC017">DOC017 — Simulated doctor</option></select></div><div class="field"><label>Scenario</label><select id="mlScenario"><option value="normal">Normal hospital work</option><option value="download2">Two downloads from unknown device</option><option value="bulk">Bulk record access</option><option value="critical">Export All insider simulation</option></select></div><button class="button" id="runPrediction">Run ML prediction</button></div></article><article class="panel"><h3>AI explanation</h3><div id="mlExplanation"><p>Run a scenario to see anomaly score, confidence, baseline comparison, and containment decision.</p></div></article></div>
  <article class="panel"><div class="panel-heading"><div><h3>Prediction history</h3><p>Latest Isolation Forest classifications.</p></div><button class="text-button" id="refreshPredictions">Refresh</button></div><div class="table-wrap"><table><thead><tr><th>Time</th><th>Doctor</th><th>Prediction</th><th>Anomaly</th><th>Confidence</th><th>Risk</th><th>Explanation</th></tr></thead><tbody id="predictionRows"></tbody></table></div></article>`;
  document.getElementById('generateMl').onclick=async()=>{try{toast('Generating 1,200 reports and 60-day history…');const d=await api('/api/ml/generate',{method:'POST',body:JSON.stringify({reports:1200,days:60})});toast(`Generated ${d.reports} reports and ${d.samples} behavior samples.`);loadStatus()}catch(e){toast(e.message)}};
  document.getElementById('trainMl').onclick=async()=>{try{toast('Training Isolation Forest…');const d=await api('/api/ml/train',{method:'POST',body:'{}'});toast(`Model ${d.model.version} trained.`);loadStatus();loadPredictions()}catch(e){toast(e.message)}};
  document.getElementById('runPrediction').onclick=runPrediction; document.getElementById('refreshPredictions').onclick=loadPredictions;
  loadStatus();loadPredictions();
 }
 const scenarios={normal:{login_hour:8.4,session_minutes:470,records_viewed:24,downloads:2,departments_accessed:1,failed_logins:0,unknown_device:0,external_ip:0,after_hours:0,export_all:0},download2:{login_hour:2.2,session_minutes:12,records_viewed:8,downloads:2,departments_accessed:2,failed_logins:1,unknown_device:1,external_ip:1,after_hours:1,export_all:0},bulk:{login_hour:1.8,session_minutes:20,records_viewed:430,downloads:36,departments_accessed:7,failed_logins:2,unknown_device:1,external_ip:1,after_hours:1,export_all:0},critical:{login_hour:2.1,session_minutes:9,records_viewed:1250,downloads:180,departments_accessed:10,failed_logins:4,unknown_device:1,external_ip:1,after_hours:1,export_all:1}};
 async function runPrediction(){try{const doctor_id=document.getElementById('mlDoctor').value;const s=document.getElementById('mlScenario').value;const d=await api('/api/ml/predict',{method:'POST',body:JSON.stringify({doctor_id,...scenarios[s]})});const x=d.result;const action=x.risk==='Critical'?'Export blocked · session terminated · account restricted · incident report created':x.risk==='High'?'Sensitive exports restricted · incident opened':x.risk==='Medium'?'Administrator notified · session monitored':'Allow and audit';document.getElementById('mlExplanation').innerHTML=`<div class="metric-value">${esc(x.anomalyScore)}</div><p><strong>${esc(x.risk)} risk · ${esc(x.confidence)}% confidence</strong></p><ul>${x.reasons.map(r=>`<li>${esc(r)}</li>`).join('')}</ul><div class="notice"><strong>Decision:</strong> ${esc(action)}</div>`;toast(`ML classified activity as ${x.risk}.`);loadPredictions()}catch(e){toast(e.message)}}
 async function loadStatus(){try{const d=await api('/api/ml/status');document.getElementById('mlStatus').textContent=d.active?'Active':(d.model?'Stored':'Not trained');document.getElementById('mlSamples').textContent=Number(d.dataset?.samples||0).toLocaleString();document.getElementById('mlDoctors').textContent=d.dataset?.doctors||0}catch(e){}}
 async function loadPredictions(){try{const d=await api('/api/ml/predictions');const el=document.getElementById('predictionRows');if(!el)return;el.innerHTML=(d.predictions||[]).map(x=>`<tr><td>${esc(x.created_at)}</td><td>${esc(x.doctor_id)}</td><td>${esc(x.prediction)}</td><td>${esc(x.anomaly_score)}</td><td>${esc(x.confidence)}%</td><td><span class="badge ${String(x.risk_level).toLowerCase()}">${esc(x.risk_level)}</span></td><td>${esc(JSON.parse(x.reasons||'[]').join('; '))}</td></tr>`).join('')||'<tr><td colspan="7">No predictions yet. Train the model and run a scenario.</td></tr>'}catch(e){}}
 async function reportsPage(offset=0){const p=document.getElementById('page-reports');if(!p)return;p.innerHTML='<div class="intro-row"><div><h2>Patient Reports Dataset</h2><p>Loading the Phase 9 report library…</p></div></div>';try{const d=await api(`/api/ml/reports?limit=100&offset=${offset}`);p.innerHTML=`<div class="intro-row"><div><h2>Patient Reports Dataset</h2><p>${Number(d.total).toLocaleString()} realistic lab, scan, diagnostic, and clinical reports used by the hospital demo.</p></div><div class="actions"><button class="button secondary" onclick="window.print()">Print</button><button class="button" id="reportExport">Export visible CSV</button></div></div><div class="notice"><strong>Dataset range:</strong> Phase 9 supports 500–2,000 generated patient reports. The included database contains ${Number(d.total).toLocaleString()} reports.</div><article class="panel"><div class="table-wrap"><table><thead><tr><th>Report ID</th><th>Patient</th><th>Age/Gender</th><th>Blood</th><th>Report</th><th>Doctor</th><th>Department</th><th>Status</th><th>Generated</th></tr></thead><tbody>${d.reports.map(r=>`<tr><td>${esc(r.report_id)}</td><td>${esc(r.patient_name)}<br><small>${esc(r.patient_id)}</small></td><td>${esc(r.age)} / ${esc(r.gender)}</td><td>${esc(r.blood_group)}</td><td>${esc(r.report_type)}</td><td>${esc(r.doctor_name||r.doctor_id)}</td><td>${esc(r.department)}</td><td>${esc(r.status)}</td><td>${esc(r.generated_at)}</td></tr>`).join('')}</tbody></table></div></article><div class="actions"><button class="button secondary" id="prevReports" ${offset<=0?'disabled':''}>Previous</button><button class="button" id="nextReports" ${offset+100>=d.total?'disabled':''}>Next 100</button></div>`;document.getElementById('prevReports').onclick=()=>reportsPage(Math.max(0,offset-100));document.getElementById('nextReports').onclick=()=>reportsPage(offset+100);document.getElementById('reportExport').onclick=()=>{const rows=[['Report ID','Patient','Patient ID','Report Type','Doctor','Department','Status','Generated'],...d.reports.map(r=>[r.report_id,r.patient_name,r.patient_id,r.report_type,r.doctor_name||r.doctor_id,r.department,r.status,r.generated_at])];const csv=rows.map(a=>a.map(v=>'"'+String(v??'').replace(/"/g,'""')+'"').join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='wecare-visible-reports.csv';a.click();URL.revokeObjectURL(a.href)}}catch(e){p.innerHTML=`<div class="notice">${esc(e.message)}. Generate the dataset from ML Prediction.</div>`}}
 document.querySelector('[data-page="predictions"]')?.addEventListener('click',()=>setTimeout(predictionPage,20));document.querySelector('[data-page="reports"]')?.addEventListener('click',()=>setTimeout(()=>reportsPage(0),20));
 try{const s=io();s.on('ml:prediction',x=>toast(`AI prediction: ${x.doctorId} is ${x.risk}`));s.on('ml:model-trained',x=>toast(`Isolation Forest ${x.version} is active.`))}catch(_e){}
})();
